PollBuddy/PollBuddy

PollBuddy-Server/backend/routes/groups.js
PollBuddy-Server/backend/routes/polls.js

Implemented delete functionality and fixed minor bugs in groups and polls

---

PollBuddy-Server/frontend/Login Page/login.js
PollBuddy-Server/frontend/Login Page/login.scss

Created PollBuddy's Login Page

Login page

---

PollBuddy-Server/frontend/src/pages/Login Page/login.js
PollBuddy-Server/frontend/src/pages/myclasses/myclasses.js

minor problems in getting things to happen. Sometimes reroutes without re-rendering...
PROB SHOULD BE ADDRESSED BEFORE MERGING

Implemented session/localstorage hopefully

---

PollBuddy-Server/frontend/src/pages/template/template.js
PollBuddy-Server/package-lock.json

Want to eventually make template class into a backent testing tool so we don't have to do that atrocious curl stuff to do pull requests etc.
This is the first iteration of this... successfully displayed get requests and stuff... 
- [ x] New feature (non-breaking change which adds functionality)
Class editing which will be done in another branch maybe
- (none)
- Closes #XXXX

Template page improved to display information better

---

PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/pages/forgotPassword/forgotPassword.js
PollBuddy-Server/frontend/src/pages/forgotPassword/forgotPassword.scss
PollBuddy-Server/frontend/src/pages/forgotPassword/index.js

Added header with disposable logo, email input, sign in button, and submission box.
Created the forgot password page as designed in the google slides
- Link the buttons to necessary pages and backend involvement
- Closes #102

Forgot password page

---

PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/pages/pollCode/index.js
PollBuddy-Server/frontend/src/pages/pollCode/pollCode.js
PollBuddy-Server/frontend/src/pages/pollCode/pollCode.scss

Featuring an input box, logo which will be changed, and a enter poll button
Created the Poll Code entry page with a disposable logo that will be replaced
- Link necessary backend features for entry actions
- Closes #104

Enter poll code page

---

PollBuddy-Server/backend/routes/groups.js
PollBuddy-Server/backend/routes/users.js

Merging users routes into backend

Users route

---

PollBuddy-Server/frontend/src/pages/accountinfo/accountinfo.scss

Quick bug fix to keep the logo center.
-  Bug fix (non-breaking change which fixes an issue)
- (none)

Centered the "Account Info " text

---

PollBuddy-Server/frontend/package-lock.json
PollBuddy-Server/frontend/package.json

Updated to React 3.4.1. We were a few versions below.
Version change
-  Bug fix (non-breaking change which fixes an issue)
- (none)
- Closes #145

Updated to React version 3.4.1

---

PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/pages/privacy/privacy.js
PollBuddy-Server/frontend/src/pages/privacy/privacy.scss

Added simple privacy page.
-  New feature (non-breaking change which adds functionality)
- Add new header and new footer once components are merged
- Closes #122

Privacy page

---

PollBuddy-Server/frontend/package.json
PollBuddy-Server/package-lock.json

The react update to 3.4.1 broke it, seems they pushed a fix hours ago so I'm basically just implementing it early.
- (none)
- Probably should have had an issue but that didn't happen so no issues to close lol

Fixed frontend not starting in Docker

---

PollBuddy-Server/frontend/src/pages/privacy/privacy.js
PollBuddy-Server/frontend/src/pages/privacy/privacy.scss

The old header was still in when this page got merged to frontend. This change changes to the new header and cleans up the page as well/
-  Bug fix (non-breaking change which fixes an issue)
- (none)
- Closes #165

Changed Privacy Page Header

---

PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/pages/pollDataView/index.js
PollBuddy-Server/frontend/src/pages/pollDataView/pollDataView.js
PollBuddy-Server/frontend/src/pages/pollDataView/pollDataView.scss
PollBuddy-Server/frontend/src/pages/resetPassword/index.js
PollBuddy-Server/frontend/src/pages/resetPassword/resetPassword.js
PollBuddy-Server/frontend/src/pages/resetPassword/resetPassword.scss

Created the pollDataView page (teacher view) with a list of question buttons on the left. On the right is a bar graph with the number of people who chose each option.
- get list of questions and answers from backend
- Closes #110

Poll data view

---

PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/pages/resetPassword/index.js
PollBuddy-Server/frontend/src/pages/resetPassword/resetPassword.js
PollBuddy-Server/frontend/src/pages/resetPassword/resetPassword.scss

Created the Reset Password page. On the issues page, this is called the Forgot password (step 2) page, but I think Reset Password is more descriptive.
- Autofill the security code in the text box
- Determine if clicking the Submit button should go to the login page, the myclasses page, or the accountinfo page
- Closes #103

Reset password

---

PollBuddy-Server/README.md
PollBuddy-Server/backend/.env.example
PollBuddy-Server/backend/modules/mongoConnection.js
PollBuddy-Server/backend/package-lock.json
PollBuddy-Server/frontend/.env
PollBuddy-Server/frontend/.env.example
README.md

Added example .env files with documentation, updated main README and PollBuddy-Server README files with better documentation. Preparing for frontend-backend proxy server. 
- Will take and adapt with the frontend-backend proxy server creation.

.env changes and documentation updates

---

PollBuddy-Server/frontend/package-lock.json
PollBuddy-Server/frontend/package.json
PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/components/header/header.js
PollBuddy-Server/frontend/src/pages/Login Page/login.js
PollBuddy-Server/frontend/src/pages/accountinfo/accountinfo.js
PollBuddy-Server/frontend/src/pages/classcreation/classcreation.js
PollBuddy-Server/frontend/src/pages/forgotPassword/forgotPassword.js
PollBuddy-Server/frontend/src/pages/homepage/homepage.js
PollBuddy-Server/frontend/src/pages/lessons/lessons.js
PollBuddy-Server/frontend/src/pages/myclasses/myclasses.js
PollBuddy-Server/frontend/src/pages/notfound/notfound.js
PollBuddy-Server/frontend/src/pages/pollCode/pollCode.js
PollBuddy-Server/frontend/src/pages/pollDataView/pollDataView.js
PollBuddy-Server/frontend/src/pages/privacy/privacy.js
PollBuddy-Server/frontend/src/pages/registerDefault/registerDefault.js
PollBuddy-Server/frontend/src/pages/registerWithPollBuddy/registerWithPollBuddy.js
PollBuddy-Server/frontend/src/pages/registerWithSchool/registerWithSchool.js
PollBuddy-Server/frontend/src/pages/resetPassword/resetPassword.js
PollBuddy-Server/frontend/src/pages/template/template.js

- Removed Reach Router, replaced with React BrowserRouter
- Moved header, footer into App.js so it only has to be declared once and all pages get it
- Changed the way page titles work to be more coherent and flexible
- Changed registerDefault's buttons to match the other pages, styling still needed though (will be part of bulk CSS deduplication, unifying)
- CSS Cleanup/Duplication/Unification

Header footer move, other cleanup tasks

---

PollBuddy-Server/frontend/src/pages/Login Page/login.js

"login" button on login page wasn't sending you to /myClasses because of old Redirect code. This just fixes that basically.

Fixed the redirecting on the login page

---

PollBuddy-Server/backend/app.js
PollBuddy-Server/backend/package.json
PollBuddy-Server/backend/routes/users.js

Added authentication routes and session handling in the backend
?
- Closes #XXXX

Authentication

---

.github/workflows/Lint-Backend.yml
PollBuddy-Server/backend/.eslintignore
PollBuddy-Server/backend/.eslintrc.json
PollBuddy-Server/backend/app.js
PollBuddy-Server/backend/modules/mongoConnection.js
PollBuddy-Server/backend/package-lock.json
PollBuddy-Server/backend/package.json
PollBuddy-Server/backend/routes/groups.js
PollBuddy-Server/backend/routes/polls.js
PollBuddy-Server/backend/routes/users.js

Added ESLint action for backend, see frontend's PR for other details
- There's 63 warnings, may create issues for each file of things to correct, or just 1 big one, not sure. 
- Shouldn't really have any conflicts like the frontend one would, should just easily merge

Backend ESLint Workflow

---

PollBuddy-Server/frontend/.env.example
PollBuddy-Server/frontend/Dockerfile
PollBuddy-Server/frontend/package.json
PollBuddy-Server/frontend/src/components/classEditor/classEditor.js
PollBuddy-Server/frontend/src/pages/classcreation/classcreation.js
PollBuddy-Server/frontend/src/pages/lesson/lesson.js
PollBuddy-Server/frontend/src/pages/loginPage/login.js
PollBuddy-Server/frontend/src/pages/myclasses/myclasses.js
PollBuddy-Server/frontend/src/pages/template/template.js
PollBuddy-Server/webproxy/conf.d/default.conf
docker-compose.yml

Added an NGINX frontend web proxy so that we access one URL (usually localhost) at port 7655, and we'll reach the frontend react server. Any requests to /api* will be routed to the backend server instead. This will allow better frontend-backend communication and be essential when we deploy. 
- Caching should probably be configured as nginx is good at that, but that can wait. 
- It will be essential for people to reset their .env setup for frontend-backend communication to work right. 
- Closes #137
- Closes #36

Nginx web proxy

---

PollBuddy-Server/frontend/package-lock.json
PollBuddy-Server/frontend/package.json
PollBuddy-Server/frontend/src/pages/privacy/privacy.js
PollBuddy-Server/frontend/src/pages/privacy/privacy.md

Merging the added markdown support from the privacy page branch

Merging for markdown support

---

docker-compose.yml

Added explicit networking definitions in the Docker-Compose file as that allows a bit more separation of services for security, and will likely be helpful in the CI/CD pipeline(s).
- Will need to add other containers once they get merged in
- Closes #10

Added explicit Docker-Compose networking

---

PollBuddy-Server/backend/.eslintrc.json
PollBuddy-Server/backend/app.js
PollBuddy-Server/backend/routes/users.js
PollBuddy-Server/frontend/.eslintrc.json
PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/components/classEditor/classEditor.js
PollBuddy-Server/frontend/src/components/footer/footer.js
PollBuddy-Server/frontend/src/components/question/index.js
PollBuddy-Server/frontend/src/components/question/question.js
PollBuddy-Server/frontend/src/pages/accountinfo/accountinfo.js
PollBuddy-Server/frontend/src/pages/classcreation/classcreation.js
PollBuddy-Server/frontend/src/pages/faq/faq.js
PollBuddy-Server/frontend/src/pages/forgotPassword/forgotPassword.js
PollBuddy-Server/frontend/src/pages/homepage/homepage.js
PollBuddy-Server/frontend/src/pages/lesson/lesson.js
PollBuddy-Server/frontend/src/pages/lessons/lessons.js
PollBuddy-Server/frontend/src/pages/loginPage/login.js
PollBuddy-Server/frontend/src/pages/myclasses/myclasses.js
PollBuddy-Server/frontend/src/pages/notfound/notfound.js
PollBuddy-Server/frontend/src/pages/pollviewer/pollviewer.js
PollBuddy-Server/frontend/src/pages/privacy/privacy.js
PollBuddy-Server/frontend/src/pages/registerDefault/registerDefault.js
PollBuddy-Server/frontend/src/pages/registerWithPollBuddy/registerWithPollBuddy.js
PollBuddy-Server/frontend/src/pages/registerWithSchool/registerWithSchool.js
PollBuddy-Server/frontend/src/pages/resetPassword/resetPassword.js
PollBuddy-Server/frontend/src/pages/template/template.js

Added a rule to make sure semicolons are used (like at the end of lines) consistently. 
- This is set to merge to frontend because I thought I'd do separate ones for frontend/backend but didn't end up doing that, but am based off the frontend branch. Oops. They're all due to be merged anyways so it's not the end of the world but definitely my bad, do as I say not as I do lol
- Closes #230

Eslint semicolon check

---

README.md

Added site map link to the readme to allow easy access to view the map. 
- Implement code
- Update sitemap labels
- None

Add sitemap link to readme

---

PollBuddy-Server/frontend/src/components/classEditor/classEditor.js
PollBuddy-Server/frontend/src/pages/accountinfo/accountinfo.js
PollBuddy-Server/frontend/src/pages/forgotPassword/forgotPassword.js
PollBuddy-Server/frontend/src/pages/homepage/homepage.js
PollBuddy-Server/frontend/src/pages/loginPage/login.js
PollBuddy-Server/frontend/src/pages/registerWithPollBuddy/registerWithPollBuddy.js
PollBuddy-Server/frontend/src/pages/registerWithSchool/registerWithSchool.js
PollBuddy-Server/frontend/src/pages/resetPassword/resetPassword.js
PollBuddy-Server/frontend/src/styles/header.scss
PollBuddy-Server/frontend/src/styles/main.scss

Added aria-label in multiple input boxes
Changed login button text color
WAVE evaluates no errors
According to WAVE evaluation tool, we have labelling errors and contrast errors.
Added aria-label in multiple input boxes
Changed login button text color
- Further evaluation needs to be made if we wish to implement a dark/light mode switch
- Closes #199 #37

Improved accessibility

---

PollBuddy-Server/frontend/src/pages/homepage/homepage.js

Replaced the homepage blurb with the one from #183
- (none)
- Closes #183

Update homepage blurb

---

PollBuddy-Server/frontend/package-lock.json
PollBuddy-Server/frontend/package.json
PollBuddy-Server/frontend/src/components/question/question.js

I just changed the package name to the updated version to fix the deprecation issue. That's all there really is to it :)
- N/A
- Closes #194 
No visual change

Patched Deprecated Package

---

PollBuddy-Server/frontend/package.json
PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/components/footer/footer.js
PollBuddy-Server/frontend/src/pages/contactUs/contactUs.js

I have added a contact page, with links to our GitHub homepage, opening an issue on our repo, and a hypothetical email address. Besides this, I've also designed a form to submit a support ticket, featuring some fun new packages that auto-format phone numbers and the `textarea` input. The form is hidden on load and can be shown with a button. It will then hide again after submission. This was done to not have a scrolling page/information overload initially upon presentation.
- Change the color of links
- Form validation
- Form data submission
- Closes #208 
_Page did not exist before_
_After (form closed / open):_

Contact Page

---

PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/components/footer/footer.js
PollBuddy-Server/frontend/src/pages/about/about.js
PollBuddy-Server/frontend/src/pages/about/about.md
PollBuddy-Server/frontend/src/pages/privacy/privacy.js
PollBuddy-Server/frontend/src/styles/main.scss

Created an about page so that users can learn what Poll Buddy is and the purpose it serves. This page utilizes the react-markdown package.
- Paragraphs in all markdown pages use the `<p>` tag, so styling makes paragraphs have centered text. I'm not sure if this looks the best on these pages.
- The markdown issue with tables and other elements being unstyled still exists. However, we previously decided to wait and deal with that if it becomes necessary since we likely won't need a general fix for this.
- Closes #209

About Page

---

.github/workflows/CD.yml
.github/workflows/CI.yml

Created a CI-CD workflow setup: 
- Automatic deployments of branch `master` to [pollbuddy.app](https://pollbuddy.app)
- Automatic deployments of commits and PRs to [dev.pollbuddy.app](https://dev.pollbuddy.app) (using format of `dev-<commit ID>.pollbuddy.app`) 
- New repo: [PollBuddy.app][https://github.com/PollBuddy/PollBuddy.app] to house the containers for running the main and dev sites. 
- New repo: [Ci-CD][https://github.com/PollBuddy/CI-CD] to house the scripts run by the CI-CD server. Main ones currently are deployMaster.sh, deployTestInstance.sh, and getPort.sh. Upcoming are periodicDelete.sh and periodicShutdown.sh
- CI and CD GitHub Workflow files
- Various repository "secrets" to facilitate communication to the CI-CD server from GitHub's servers.
- Pull Requests *should* get a …

CI-CD Setup

---

PollBuddy-Server/reporting/grafana/config.ini
PollBuddy-Server/webproxy/conf.d/default.conf
docker-compose.yml

Removed exposed ports from frontend, backend, db, grafana, replaced with webproxy for all access
Added <url>/reporting for accessing Grafana
Added restart policies to all containers so that they'll come back up after you reboot/restart Docker. Avoid by simply running `docker-compose down`
- Webproxy will eventually log requests to InfluxDB/Grafana
- Closes #229

Docker changes: removed excess exposed ports, added restart policies

---

PollBuddy-Server/backend/package-lock.json
PollBuddy-Server/backend/package.json

Updated bcrypt (priority) and other packages (up to max allowed thru npm update)
- (none)
- (none)
- (none)

Update all backend packages

---

PollBuddy-Server/frontend/package-lock.json
PollBuddy-Server/frontend/package.json

Updated create-react-app (priority) and other packages (up to max allowed thru npm update)
- (none)
- Closes #224

Updated Create-React-App, other semantic versioned packages

---

PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/pages/answerRecorded/answerRecorded.js
PollBuddy-Server/frontend/src/pages/pollviewer/pollviewer.js
PollBuddy-Server/frontend/src/pages/questionEnded/questionEnded.js

Added the answerRecorded and questionEnded pages. After you answer the poll in the pollviewer page, it goes to answerRecorded. After the question ends, it goes to the questionEnded page.
- add the loading wheel to the questionEnded page
- Closes #205

answerRecorded and questionEnded pages

---

PollBuddy-Server/backend/.env.example
PollBuddy-Server/backend/app.js
PollBuddy-Server/backend/modules/cas.js
PollBuddy-Server/backend/package-lock.json
PollBuddy-Server/backend/package.json
PollBuddy-Server/backend/public/pages/loginRedirect.html
PollBuddy-Server/backend/routes/users.js
PollBuddy-Server/frontend/.env.example
PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/components/header/header.js
PollBuddy-Server/frontend/src/pages/homepage/homepage.js
PollBuddy-Server/frontend/src/pages/loginDefault/loginDefault.js
PollBuddy-Server/frontend/src/pages/loginPage/login.js
PollBuddy-Server/frontend/src/pages/loginWithSchool/loginWithSchool.js

Added the loginWithSchool page. It's pretty much the same as registerWithSchool. Also, added a link to get to this page through the login page.
- (none)
- Closes #217 
loginWithSchool page
login page

Login with school

---

PollBuddy-Server/frontend/src/components/SchoolPicker/SchoolPicker.js
PollBuddy-Server/frontend/src/pages/LoginWithSchool/LoginWithSchool.js
PollBuddy-Server/frontend/src/pages/RegisterWithSchool/RegisterWithSchool.js

This PR should fix the autoselect dropdown styling issues in login
with the school page. It also extracts that dropdown to a new SchoolPicker
component because it is used in (at least) 2 places
- (none)
- https://github.com/PollBuddy/PollBuddy/issues/280
| Before             |  After |
:-------------------------:|:-------------------------:

Fix styling issues in login with school page

---

PollBuddy-Server/frontend/src/pages/About/About.js
PollBuddy-Server/frontend/src/pages/About/About.md
PollBuddy-Server/frontend/src/pages/AccountInfo/AccountInfo.js
PollBuddy-Server/frontend/src/pages/Contact/Contact.js
PollBuddy-Server/frontend/src/pages/Contact/Contact.scss
PollBuddy-Server/frontend/src/pages/GroupPolls/GroupPolls.js
PollBuddy-Server/frontend/src/pages/GroupPolls/GroupPolls.scss
PollBuddy-Server/frontend/src/pages/Login/Login.js
PollBuddy-Server/frontend/src/pages/PollViewer/PollViewer.scss
PollBuddy-Server/frontend/src/pages/Privacy/Privacy.md
PollBuddy-Server/frontend/src/pages/RegisterWithPollBuddy/RegisterWithPollBuddy.js
PollBuddy-Server/frontend/src/pages/RegisterWithSchool/RegisterWithSchool.js
PollBuddy-Server/frontend/src/pages/ResetPassword/ResetPassword.js
PollBuddy-Server/frontend/src/styles/main.scss

- privacy markdown reformatted
- update contact and about pages to use the new theme
- password placeholders standardized and password fields restyled bc current styling makes the difference between password placeholder and text jarring
- type="password" added to input fields where it was missing
- added another input field to accountinfo so changing password makes more sense (new password/confirm new/confirm old)
- misc css cleanup
- (none)
- Closes #277 #248 #247 #246

Page content/styling fixes and css cleanup

---

README.md
docker-compose.yml

Addition of many things detailed in issue #260 , with two exceptions that are detailed in the "other concerns" section. The Readme in its old form had a lot of details that were omitted or just incorrect (outdated); this is a major pass updating everything for easier use by new developers.
- (Fixed with commit 3286ff1) ~~The logo is not yet included on the top; this will be done soon after we establish a permanent home for it on.~~
- (Fixed with commit 588916f) ~~The database access is not yet described; Hunter has said he will do this in a later issue as it is more complex than anything else in this issue (I have it noted as TOFIX but can put some other placeholder or remove this entirely if wanted)~~
- Closes #260 ~~(we will open a new issue for the database access details)~~

Readme Updates

---

PollBuddy-Server/frontend/src/pages/FAQ/faq.md
README.md

I made a Wiki for the repo. For the home page I just added the logo to make it nicer. I created a new page for installation instructions and moved the instructions from the readme and added some more things that might make it easier for the person reading and installing. I put the link to this in the main readme and in FAQ page on Poll Buddy. I edited the Wiki right on the Wiki page so it's at https://github.com/PollBuddy/PollBuddy/wiki/Installation-Instructions 
Also if we seem to like the Wiki and want to continue to use it I feel like we can add a page that gives instructions to how new Poll Buddy members can start contributing that like basically explains how to make a branch and pull request and stuff because I was confused on that at first but that can be its own issue if we like …

Adding wiki links

---

PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/pages/AccountInfo/AccountInfo.js
PollBuddy-Server/frontend/src/pages/AdminSettings/AdminSettings.js
PollBuddy-Server/frontend/src/pages/Groups/Groups.js
PollBuddy-Server/frontend/src/pages/MemberSettings/MemberSettings.js
PollBuddy-Server/frontend/src/styles/main.scss

Edited account page: Since the page is called account info, it should have read-only information about the user. So, I removed the text boxes for name, email, and password. I added a button for changing the password.
Created admin settings page and member settings page which users can access from the groups page through an edit button. The admin settings page allows the user to change the group name, add and remove students, and delete the group. The member settings page allows the user to leave the group. Both pages display read-only information about the polls and the number of correct answers.
- (none)
- Closes #124

Settings and account

---

PollBuddy-Server/frontend/package-lock.json
PollBuddy-Server/frontend/package.json
PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/components/ErrorText/ErrorText.js
PollBuddy-Server/frontend/src/components/ErrorText/ErrorText.scss
PollBuddy-Server/frontend/src/components/GroupEditor/GroupEditor.js
PollBuddy-Server/frontend/src/pages/GroupCreation/GroupCreation.js
PollBuddy-Server/frontend/src/pages/GroupEdit/GroupEdit.js
PollBuddy-Server/frontend/src/pages/GroupEditor/GroupEditor.js
PollBuddy-Server/frontend/src/pages/Template/Template.js

Cleaned up backend functionality with the group creation/editor component. It now redirects to the group/pollid/polls page when you create a new group. Added code to hide the loading wheel when necessary. Made a new error text component and showed it when the backend returns an error.
- Need backend functionality for checking if a user is logged in and we need some way to add polls and users/instructors
- Closes #273

Group creation functionality

---

PollBuddy-Server/backend/Dockerfile
PollBuddy-Server/backend/Dockerfile.lint
PollBuddy-Server/frontend/Dockerfile
PollBuddy-Server/frontend/Dockerfile.lint
docker-compose.lint.yml

Added a method to run the lint tests locally so you don't have to rely on the automated checks if you don't want to. Run it with `docker-compose -f docker-compose.lint.yml up --build`
- (none)
- Closes #245

Docker lint mode

---

PollBuddy-Server/frontend/src/pages/Homepage/Homepage.js

Fixed the register button on the homepage to go to /register instead of /registerDefault
- (none)
- Closes #259

Homepage register fix

---

PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/components/PollCode/PollCode.js
PollBuddy-Server/frontend/src/pages/Code/Code.js
PollBuddy-Server/frontend/src/pages/Homepage/Homepage.js

Created a component for the "enter poll code" box which looks exactly the same and has the same functionality, which I then added onto the homepage. Then, I created a new page and added the PollCode component onto that page.
- add a link from the header dropdown to the /code page
- Closes #312 
Homepage looks the same
Here's the code page

Poll code component

---

PollBuddy-Server/frontend/src/App.js

Commented all routes inside src/App.js
https://github.com/PollBuddy/PollBuddy/issues/324
- (none)
- Closes #324

Commented all routes in App.js

---

PollBuddy-Server/frontend/package-lock.json
PollBuddy-Server/frontend/package.json
PollBuddy-Server/frontend/src/components/Question/Question.js
PollBuddy-Server/frontend/src/components/Question/Question.scss
PollBuddy-Server/frontend/src/pages/PollViewer/PollViewer.js
PollBuddy-Server/frontend/src/pages/Template/Template.js

Updated the question component to use pollbuddy's new style guides and fixed the timer.
- The width of the bubbles that contain the answer choices (A, B, C, ect) fits the text inside but I don't know how to make the height always match the width 
- Here is the json structure that the question component accepts
```
{
"questionNumber": "3",
"question": "Why does the tooth fairy collect teeth?",
"img": "https://i.kym-cdn.com/photos/images/newsfeed/001/409/553/5f5.png",
"choices": [
"She grinds them into the fairy dust she needs to fly",
"She gives them to new babies who are ready to grow teeth",
"She gives the good teeth to dentists to make false teeth",
"She grinds them up and makes sand for the beach",
"She needs to replace her own teeth",
],
"points": 2,
"maxAllowedChoices": 2, …
```

Question update

---

PollBuddy-Server/frontend/src/components/questionEditor/questionEditor.js
PollBuddy-Server/frontend/src/components/questionEditor/questionEditor.scss

Salvage old questionEditor component in ancient branch.
- Maybe updates to questionEditor is needed.
- Closes #255

moved questionEditor to the current branch.

---

PollBuddy-Server/backend/routes/groups.js
PollBuddy-Server/backend/routes/polls.js
PollBuddy-Server/backend/routes/users.js

remove trailing slashs at the end of backend route pathes.
- (none)
- Closes #379

Backend route trailing slash fix

---

README.md

I finished the contribution guide wiki and I put a link to it in the Readme
- (none)
- Closes #143

Finished contribution guide

---

CONTRIBUTING.md

In the CONTRIBUTION.md page I just put a link to the Contribution guide wiki instead of rewriting all the instructions in the md file. This was for the file that was shown in the small group meeting.
- (none)
- Closes #143

linked contribution guide wiki in contribution.md

---

PollBuddy-Server/frontend/src/pages/Groups/Groups.js
PollBuddy-Server/frontend/src/styles/main.scss

I added the functionality for users to leave groups. On the My Groups page under Group Management, I added a button Leave Group. When clicked, an "X" appears next to each of the groups that the user is a member of. When the "X" is clicked, a pop up appears asking the user to confirm that they want to leave the group. When the pop up closes, the user is still in Leave Group mode until they click Exit Leave Group to get rid of the "X"s.
- If you click "YES" to confirm leaving a group, a backend request needs to be sent to drop the user from the group and remove the group from the page if successful.
- Closes #108

Leave group functionality

---

PollBuddy-Server/backend/package-lock.json
PollBuddy-Server/backend/package.json
PollBuddy-Server/frontend/src/App.js

When I finished this task, I find I misunderstand the request that I comment each route instead of each block. Also when I commit my work, I find there already exists route block comment. I am not sure whether I should keep each route comment but I think that might be a good supplement
- (none)
- Closes #324

Frontend route group commenting

---

PollBuddy-Server/backend/app.js
PollBuddy-Server/backend/routes/users.js
PollBuddy-Server/frontend/src/pages/Groups/Groups.js
PollBuddy-Server/frontend/src/pages/Homepage/Homepage.js
PollBuddy-Server/frontend/src/pages/LoginWithPollBuddy/LoginWithPollBuddy.js

Moved user cookie system to backend using express session. Stores login state, email and password.
- Maybe add username field too?
- N/A

use express-session to store logged in state

---

PollBuddy-Server/backend/app.js
PollBuddy-Server/backend/modules/cas.js
PollBuddy-Server/backend/modules/rpi.js
PollBuddy-Server/backend/modules/schoolList.js
PollBuddy-Server/backend/routes/users.js

Added a (currently hard-coded) array of possible schools into the backend for access by future API calls. At the moment the schools were hard-coded into the frontend, which is worse practice and less easily expandable in the future.
- Closes #300

Added /api/schools request

---

PollBuddy-Server/backend/routes/polls.js

Reworked the aforementioned endpoint to have more error checking and to return the ID of the new poll so the frontend can redirect to the edit page properly. Data returned is as follows: 
```
{ 
"Result": "Success", 
"ID": result.insertedId 
}
```
- Further validation needed, see TODO in code.
- Documentation needs to be added to the code and the Wiki. An issue will be created at merge time. 
- A common format should be made for backend data. I think a "Result" part would be nice, as well as "Error" when relevant. This should be explored, documented, and implemented. An issue will be created at merge time. 
- There may not have been one oops. Please add if anyone finds one. 
- This is essential for the frontend to create polls though.

Backend /api/polls/:id/new endpoint renovations for increased usefulness 

---

PollBuddy-Server/backend/routes/polls.js

Added the aforementioned endpoint. This will return data as follows: 
```
{ 
"Questions": [ 
{
"QuestionNumber": int >= 1
"QuestionText": String
"AnswerChoices": [
"Ans1", "... etc as defined in in the database schema"
]
}
] 
}
```
- ID should be validated. I left a TODO item in the code and eventually I'll run through and make issues for all TODO items like this. 
- Documentation needs to be added to the code and the Wiki. An issue will be created at merge time. 
- There may not have been one oops. Please add if anyone finds one. 
- This is essential for the frontend to populate its questions though.
I think this will include non-relevant commits to /api/polls/new because I was working off another branch. Please ignore those. They are a separate PR.

Backend /api/polls/:id/view Endpoint

---

PollBuddy-Server/backend/routes/polls.js

Renovated /api/polls/:id/submit to work correctly (at least for anonymous users, but likely logged in users too once that works) and added some error checking. 
- Make sure it works with logged in users too
- More testing and error checking
- ¯\\\_(ツ)_/¯

Submit poll backend call

---

PollBuddy-Server/backend/routes/polls.js
PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/components/Question/Question.js
PollBuddy-Server/frontend/src/pages/PollViewer/PollViewer.js

PollViewer can now load data from the backend and submit answers :D
- Lots of work still needed though to polish it up like error checking, not allowing empty submissions, many TODOs in the code, many hardcoded things to make this work at all, etc.
- ¯\\\_(ツ)_/¯

Working poll submission

---

PollBuddy-Server/backend/routes/users.js
PollBuddy-Server/frontend/src/pages/RegisterWithPollBuddy/RegisterWithPollBuddy.js

The key change is that for backend api (user/register), it has three return values right now:
1. an error dictionary: {firstname: "Invalid firstname format!", lastname: "Invalid lastname format!"}
2. a string: Exists, which means the email address has already been registered
3. status 203: everything is ok
The last two are already existed and I add error dictionary as a new return value according to this request. 
I also modified the frontend so that it can figure out what it supposed to do based on the return values. If it accepts an error dictionary, currently I just use console.log to print it. It you need more actions, I can do that. 
According to my understanding, since we do the same checks in frontend and backend, a normal client will never get the backend error messages. However, …

Registration client side validation

---

PollBuddy-Server/frontend/src/components/Popup/Popup.js
PollBuddy-Server/frontend/src/components/Popup/Popup.scss
PollBuddy-Server/frontend/src/pages/Groups/Groups.js
PollBuddy-Server/frontend/src/styles/main.scss

I decided that presenting a popup would probably be best when the user clicks on the Join Group button. Originally, when the user clicked this button, an alert box appeared prompting the user for the group code. I preserved this functionality but used a custom popup instead. The popup contains a text field in which the user can enter the group code, and when they click "OK", they are taken to a unique URL location based on their input.
- I was having trouble with the positioning of the popup. I decided to make the popup have absolute positioning, but for some reason it is off center, and I couldn't figure out why. For now, I hard coded the bottom and right values to try to center it as best I could, but this will need to get fixed because of course it will not look right on all screen …

Join group popup

---

PollBuddy-Server/backend/routes/users.js
PollBuddy-Server/frontend/src/pages/RegisterWithPollBuddy/RegisterWithPollBuddy.js

Corrected the `users` database scheme field from `Username` to the intended `UserName`. The fix is applied to both the backend route `/users` and the frontend API calls under `page/RegisterWithPollBuddy`.
- Existing data in the db that is based on the old scheme might break.
- Closes #420 
Changes only applied to API calls.

Correct db scheme 'Username' to 'UserName'

---

PollBuddy-Server/frontend/src/pages/Groups/Groups.js
PollBuddy-Server/frontend/src/pages/Groups/Groups.scss
PollBuddy-Server/frontend/src/styles/main.scss

On the My Groups page, I fixed the leave groups functionality. When the Leave Group button is clicked, Xs now appear next to each group. When the user clicks on an X, a dialog box opens prompting the user to confirm whether they would like to leave the group.
Additionally, I changed the button text for creating a new group and joining an existing group to make it more clear to the user what these buttons do.
- A backend request will need to be made so that users can actually leave groups.
- Closes #406

Fixed leaving groups functionality

---

PollBuddy-Server/backend/modules/mongoConnection.js

Added the function validateID(ID, type) to mongoConnection.js to match the requests in issue #409. Will return true if the ID passed exists under the collection type passed, and false otherwise. 
- If anyone more experienced with mongoDB wants to look at this and approve it that would be great, since I'm still new with mongoDB.
- Closes #409

Backend docs

---

PollBuddy-Server/backend/.eslintrc.json
PollBuddy-Server/backend/modules/utils.js
PollBuddy-Server/backend/package-lock.json
PollBuddy-Server/backend/package.json
PollBuddy-Server/backend/routes/polls.js

Added npm package `Joi` to check for request body input. Created `utils.js` under `backend\modules\` for common functions such as id validation and creating a standard response. The fix also includes mongo ID validation for several routes under `api/polls`. Some bugs were the api returns a response regardless of the database promise is fixed. `eslintrc.json` is updated to emca 8 to support async functions.
NOTE: npm package [joi](https://www.npmjs.com/package/joi) required.
- Some routes under `api/polls` have not yet implement Joi request body and id validation.
- Closes #415

Request Body and ID validation

---

PollBuddy-Server/frontend/src/pages/AccountInfo/AccountInfo.js
PollBuddy-Server/frontend/src/styles/main.scss

Styled readonly inputs to make it clear that it's un-editable.
- (none)
- Closes #387 
Original
Original Focused
After
After Focused

readonly inputs

---

PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/components/Dropdown/Dropdown.js
PollBuddy-Server/frontend/src/pages/GroupJoin/GroupJoin.js
PollBuddy-Server/frontend/src/pages/Groups/Groups.js
PollBuddy-Server/frontend/src/styles/main.scss

I worked on creating the Join Group page. Previously, when a user clicked on the Join Group button on the Groups page, a popup would appear prompting them to enter the group code of the group they wanted to join. We decided to remove the popup and instead create a new page for this functionality because dynamically centering the popup on the page became a challenge. Once the user enters the group code and clicks "OK", they must confirm their decision before being redirected to that group's poll page. Additionally, if the user is not logged in when they try to join a group, they are brought to /login.
- Shows details of the group to join (only if user passes join permission checks)
- Join permissions check - group must be open join by ID, or user must be added to group's allowed to join …

Join group page

---

PollBuddy-Server/frontend/src/components/Settings/Settings.js
PollBuddy-Server/frontend/src/pages/GroupPolls/GroupPolls.js

Created a component for the settings pane on the group polls page. Creating a component for the settings pane increases modularity and reusability. The design looks the same, but now the settings component can be imported into the
group polls page.
I was also trying to add some functionality to the component, but it looks like the backend stuff will have to wait until everything is updated.
- functionality
- Some work on #323 (but shouldn't be closed yet)

Settings component

---

PollBuddy-Server/backend/modules/utils.js
PollBuddy-Server/backend/routes/polls.js

Reworked `POST /api/polls/new`, `POST /api/polls/:id/edit`, `GET /api/polls/`, and `GET /api/polls/:id` to make sure it works and followed the specifications we agreed on. Also fixed `validateID()` to make sure the supplied id exists the in database and some [documentations](https://github.com/PollBuddy/PollBuddy/wiki/Specifications-%E2%80%90-Backend-Routes-(Polls))
- Many routes should be permission guarded.
- Closes #414, #387, #362, #361, #360, #359, #352, #353, #354

Polls rework

---

PollBuddy-Server/README.md
PollBuddy-Server/backend/techList.md
PollBuddy-Server/frontend/README.md
PollBuddy-Server/frontend/techList.md
README.md

Fixed broken links in main README
Added joi to backend techList.md
Fixed some spelling errors and ran all markdown through a lint
- (none)
- (none)

Changes to README and techList

---

PollBuddy-Server/backend/routes/users.js

Conversion of bcrypt hashing and comparing into async calls that prevent 
Not 100% certain if I did this right but functions are indeed now async
- Closes #429 
N/A

Async bcrypt

---

PollBuddy-Server/frontend/src/pages/LoginWithPollBuddy/LoginWithPollBuddy.js
PollBuddy-Server/frontend/src/pages/LoginWithPollBuddy/LoginWithPollBuddy.scss

Added a counter to keep track of the number of failed user login attempts. Suggests using reset link after 5x failed attempts.
Also centered the rest of the text and added a '?' to the end of the Forgot Password link
- (none)
- Closes #263

Login Attempt Tracker

---

PollBuddy-Server/backend/routes/groups.js
PollBuddy-Server/backend/routes/polls.js

Added permission access checks to both groups and polls for user access and admin access. 
This means I had to add Admin and Group data types to polls. Admin is an array of strings of User IDs that have permission to have admin privileges on a poll. It can be empty in the case that it is linked to a group, which the Group data type stores. It contains a single string of the group ID that the poll is a part of. The wiki has been updated to reflect these changes.
- Not sure how the polls should handle user access checks when not linked to a group. At the moment it will allow anyone if there isn't a group attached to the poll, but this should be discussed.
- Closes #410

Backend permissions

---

PollBuddy-Server/backend/routes/users.js

Just some cleanups to the user routes documentation I made while I was working on the Wiki documentation.
- (none)
- (none)

Users documentation fixes

---

PollBuddy-Server/backend/.eslintrc.json
PollBuddy-Server/backend/modules/utils.js
PollBuddy-Server/backend/routes/polls.js

Reworked route `/api/polls/:id/submit`. Added a helper function `isLogedIn()` and a middleware `checkPollPublic()` to `utils.js`. Updated eslint to support emca 2018.
Documentation added:
- [new route](https://github.com/PollBuddy/PollBuddy/wiki/Specifications-%E2%80%90-Backend-Routes-(Polls)#post-idsubmit)
- [isLoggedIn](https://github.com/PollBuddy/PollBuddy/wiki/Specifications-%E2%80%90-Backend-Overview#isloggedinreq)
- [checkPollPublic](https://github.com/PollBuddy/PollBuddy/wiki/Specifications-%E2%80%90-Backend-Overview#checkpollpublic)
- Needs testing for logged in user once this is implemented in the frontend.
- Polls should implement the new `Public` attribute in the backend.
- Closes #413

Polls rework2

---

PollBuddy-Server/backend/routes/groups.js

All of the endpoints in /groups have been given javadoc style documentation in the code and updated on the wiki. I also fixed the documentation on the helper functions at the end. I tried to update the functions with more validation, but I didn't really touch /:id/edit and I will do more when I do the testing issues. This was primarily supposed to be the documentation
- do the testing issues and do more validation/change the .sendStatus to .status().send(createResponse())
- also I realized I'm not sure if we need the instructors data type, that's what the admins are for but more general to fit outside of a purely classroom setting
- #376 
- #374 
- #372 
- #370 
- #368 
- #366 
- #365 
- #363

Enpoint work

---

PollBuddy-Server/frontend/src/pages/PollEditor/PollEditor.js
PollBuddy-Server/frontend/src/pages/PollEditor/PollEditor.scss

I worked on the Poll Editor page functionality and styling. The page is organized into two content boxes; the left box is for Poll Details and the right box is the Poll Editor. The user now has the ability to update the poll title and description, edit existing poll questions, add new questions, and reorder the questions.
- Need a way to view the access permissions (open to everyone, login not required, group access, etc.) This likely will require a new call on the backend, for which an issue may not exist.
- Permissions check to ensure viewer is allowed to see the edit page
- Loading wheel while content populates
- Does not close but addresses #106

Poll editor page

---

PollBuddy-Server/frontend/src/components/ErrorText/ErrorText.js
PollBuddy-Server/frontend/src/components/ErrorText/ErrorText.scss
PollBuddy-Server/frontend/src/pages/LoginWithSchoolStep2/LoginWithSchoolStep2.js
PollBuddy-Server/frontend/src/pages/RegisterWithSchoolStep2/RegisterWithSchoolStep2.js

Implemented login system in the frontend. This includes getting data like including the firstname, lastname, username, etc. from the backend and saving it in localstorage. Also, lots of error checking for the register and login pages.
- lots of testing probably
- Closes #438

Login system frontend

---

PollBuddy-Server/backend/routes/polls.js

The endpoint can now edit everything specified under the poll [database schema](https://github.com/PollBuddy/PollBuddy/wiki/Specifications-%E2%80%90-Database-Schema).
Newly added edit options:
- Name: Name of the poll
- Public: Allow anonymous or not
- ShortCodes: Sharing shortcodes
- Admins: Admin IDs that has permission for this poll
- Group: GroupID
- Should check edit permission
- Closes #451

new edit options.

---

PollBuddy-Server/frontend/package.json
PollBuddy-Server/frontend/src/pages/LoginWithPollBuddy/LoginWithPollBuddy.js
PollBuddy-Server/frontend/src/pages/RegisterWithPollBuddy/RegisterWithPollBuddy.js
PollBuddy-Server/frontend/src/pages/RegisterWithPollBuddy/RegisterWithPollBuddy.scss
PollBuddy-Server/frontend/src/pages/RegisterWithSchoolStep2/RegisterWithSchoolStep2.js

Added input validation using joi for the login system (the following pages):
* RegisterWithPollBuddy
* LoginWithPollBuddy
* RegisterWithSchoolStep2
- (none)
- Closes #440

Login joi validation

---

PollBuddy-Server/backend/app.js
PollBuddy-Server/backend/package-lock.json
PollBuddy-Server/backend/package.json
PollBuddy-Server/frontend/package-lock.json
PollBuddy-Server/frontend/package.json
PollBuddy-Server/frontend/src/pages/About/About.js
PollBuddy-Server/frontend/src/pages/About/About.md
PollBuddy-Server/frontend/src/pages/FAQ/FAQ.js
PollBuddy-Server/frontend/src/pages/Privacy/Privacy.js
PollBuddy-Server/frontend/src/pages/Privacy/Privacy.md

Significant amount of work on updating all packages used throughout the app. As much as possible, all node dependencies should now be updated. This also fixes an issue @jbsandling found where the app failed to build with the latest node/npm versions. 
- (none)
- (none)
- (none)

Node package updates

---

PollBuddy-Server/backend/Dockerfile
PollBuddy-Server/backend/Dockerfile.dev
PollBuddy-Server/backend/Dockerfile.lint
PollBuddy-Server/reporting/grafana/Dockerfile
PollBuddy-Server/reporting/influxdb/Dockerfile
docker-compose.dev.yml
docker-compose.yml

Added a version tag to each Docker image we use so that things are more defined, and so that the debug directions wiki page I'm making will have valid commands to use. 
- (none)
- (none)
- (none)

Versioned every Docker image

---

PollBuddy-Server/frontend/README.md

Added brief, descriptive README detailing technologies used in the frontend and how it's structured. 
- (none)

added brief README for frontend

---

PollBuddy-Server/backend/README.md

Wrote a README.md for the backend folder, since there wasn't any and the frontend folder had one.
The functionality of the backend, the modules and routes, can be further expanded upon.

Wrote a backend Readme

---

PollBuddy-Server/backend/routes/users.js

Create documentation for backend route: users: /:id/
- (none)
- Progress on #344 (endpoint still needs to be fully renovated)

Documentation: [users: /:id/edit]

---

README.md

While looking into another issue, I tried to use the wiki links on the main README. Both the installation and contribution guide links took me to pages to write new entries, as they did not link to the actual pages. I updated both of these links on the README so that people would be directed to the correct wiki guides more easily.
- (none)
- (none)

Updated README wiki links

---

PollBuddy-Server/backend/routes/polls.js

Added code documentation for GET /:id/results. Also added documentation in the wiki. Fixed minor grammar mistakes in other sections of the wiki. 
- (none)
- Closes #XXXX

Wrote backend documentation for /api/polls/:id/results

---

PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/pages/ResetPassword/ResetPassword.js

Previously, when you went to a poll's id page (/polls/:id) you were sent to a 404 page. Now, we redirect this URL to the poll's view page (/polls/:id/view) to help ensure users get to the page they intended.
- (none)
- Closes #464 
Before:
After (given same URL):

Redirect /polls/:id to /polls/:id/view

---

.github/pull_request_template.md

Update the list of things to do in the PR template before submitting.
- (none)
- Closes #477

Add proper documentation notes in the PR template

---

PollBuddy-Server/frontend/src/pages/AccountInfo/AccountInfo.js
PollBuddy-Server/frontend/src/pages/ResetPassword/ResetPassword.js
PollBuddy-Server/frontend/src/pages/ResetPassword/ResetPassword.scss

-Added UI and state for "log out everywhere" button functionality
-Additionally, solved a minor bug where the "Save Changes" button anchor element would stretch and have a "clickable" width that spanned larger than the button itself
- Future changes would be sending the checkbox state to backend to initiate log out process
- 
Before:
After:

Reset password frontend

---

.github/pull_request_template.md
PollBuddy-Server/backend/.env.example
PollBuddy-Server/backend/app.js
PollBuddy-Server/backend/modules/email.js
PollBuddy-Server/backend/package-lock.json
PollBuddy-Server/backend/package.json
PollBuddy-Server/frontend/src/App.js
docker-compose.yml

I changed the routing in App.js so that the route /polls/history would not be overridden by the /polls/:pollID redirect from #496 by moving the route for history before the redirect. Also added some comments to help prevent this issue in the future.
- (none)
- Closes #503 
Before: (/polls/history gets redirected to /polls/history/view)
After:

Moved /polls/history/ route to solve redirect bug

---

PollBuddy-Server/backend/routes/polls.js
PollBuddy-Server/backend/routes/users.js

I wrote code documentation for GET users: /id/groups. I also wrote code documentation for POST /:id/delete and GET /pollAnswers after resolving my previous Github issue. 
- (none)
- Closes #XXXX

Wrote backend documentation for GET users:/:id/groups

---

PollBuddy-Server/backend/routes/users.js

Wrote documentation for users:/:id/
- (none)
- Closes #346

Backend route documentation: users: /:id/

---

PollBuddy-Server/frontend/src/components/Settings/Settings.js
PollBuddy-Server/frontend/src/components/Settings/Settings.scss
PollBuddy-Server/frontend/src/pages/PollEditor/PollEditor.js
PollBuddy-Server/frontend/src/pages/PollEditor/PollEditor.scss

Some minor button spacing issues, specifically those in the Poll pages. Additionally, a toggle for question randomization was added in situations when teachers have at least 2 questions created.
- Backend implementation and handling of randomQuestions state
Before:
After:

fixed centering of buttons, added toggle for question randomization

---

PollBuddy-Server/backend/routes/users.js
PollBuddy-Server/frontend/src/pages/AccountInfo/AccountInfo.js

I initially started working on #274, the Account Info Page. While I was working on it, it was brought to my attention that this page's functionality relied on the /me/ routes from #351. So, this PR includes both the backend /me/ routes, as well as the frontend for the Account Info page (from the "Account" link in the dropdown).
The /me/ routes include users/me, which gets the user data from the database based on the userID stored in session at login/register. There is also users/me/edit, which allows you to post changes for the user's data to the database. Finally, there is users/me/groups, which allows you to get a list of all the groups a user is a part of. These routes were designed to have the same functionality as the old users/:id routes, but they make this information easier to …

/me/ Routes and the Account Info Page

---

CONTRIBUTING.md

Fixed the link in CONTRIBUTING.md so that it now links to the Contribution (Development) Guide.
- (none)
- Closes #514

fixed link

---

.github/workflows/CI-PullRequest.yml

They renamed the master branch to main and it broke as we were targeting master. Now targeting V1.0.4. See also: https://github.com/thollander/actions-comment-pull-request
- (none)
- Closes #516

Fixed CI-PR via a different version specifier

---

PollBuddy-Server/backend/app.js
PollBuddy-Server/backend/routes/polls.js

I added status(200) to the remaining res.send that didn't already have it for consistency and clarity in the backend files.
- (none)
- Closes #469

Added status(200) to res.send

---

PollBuddy-Server/backend/Dockerfile
PollBuddy-Server/backend/Dockerfile.dev
PollBuddy-Server/backend/Dockerfile.lint
PollBuddy-Server/frontend/Dockerfile
PollBuddy-Server/frontend/Dockerfile.dev
PollBuddy-Server/frontend/Dockerfile.lint

Fix for the frontend app not starting because Node's Docker `current` tag updated to version 17, which React has a problem with. 
- (none)
- Closes #546

Locked Node version to 16

---

PollBuddy-Server/backend/Dockerfile
PollBuddy-Server/frontend/Dockerfile

Added in docker health check to frontend and backend containers
- (none)
- Closes #466

Implement Docker Health Check

---

PollBuddy-Server/frontend/src/components/Footer/Footer.js

Issue: #551
The copyright was outdated. Now it is like '2019-(currentyear)'.
- (none)
- Closes #551

Add current year to copyright

---

PollBuddy-Server/frontend/public/index.html

In an event to improve our [PageSpeed Insights score](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpollbuddy.app%2F), I found [this](https://martinratinaud.medium.com/improve-first-contentful-paint-in-react-with-this-2-cents-hack-d1c217e867f5) article, which did work and in my opinion improves the look and feel of the app, but unfortunately did not improve [the score](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdev-5660c8cc2d0cbf6029f3bfd87a6bbf9b54e1c59b.pollbuddy.app%2F) :( But, since it looks nice and can be coupled with component lazy loading later, I felt it was worth adding permanently. 
- (none)
- (none)

Loading message while React initializes

---

PollBuddy-Server/frontend/src/pages/About/About.md

Fixed typo on About page as per issue #556 
- (none)
- Closes #556 
Before
After

Fix/about page typo/jamesbalcombe83

---

PollBuddy-Server/frontend/src/pages/LoginWithSchool/LoginWithSchool.js
PollBuddy-Server/frontend/src/pages/RegisterWithSchool/RegisterWithSchool.js

- (none)
- Closes #555 
Login with School Message:
Before:
After:
Register with School Message:
Before:
After:

Change login/register with school message

---

PollBuddy-Server/backend/routes/users.js
PollBuddy-Server/frontend/src/components/Dropdown/Dropdown.js

Updates logout route to post instead of get.
- (none)
- Closes #586

Switch logout route to post 

---

README.md

Updated readme to include pictures to display features of the website with descriptions.
- (none)
- Closes #182

Update readme to include pictures

---

PollBuddy-Server/frontend/src/pages/Groups/Groups.js

Checks if the user is logged in. If they are do nothing. If they are not bounce to the login page. Added redirect to state to achieve this. Also imported Redirect from router to send to login
Added a fetch to the /me api route to check if the user is logged in. If the user is not logged in, the redirect variable is set to true and the page redirects to /login. 
- Get list of users
- Add error message checking once error messages on backend are complete
- Closes #268

Created redirect

---

PollBuddy-Server/frontend/src/pages/AccountInfo/AccountInfo.js
PollBuddy-Server/frontend/src/pages/AccountInfo/AccountInfo.scss

Updated the account info page. Added a functional password change option. Removed the confirm password box and instead added a view password function (in order to match the password creator in register with PollBuddy). I also added error message displays when the user fails to enter the correctly formatted inputs as well as a success message for when the user successfully makes their changes.
- We need some indication of login type (RCS or PollBuddy) and the option to link/unlink PollBuddy accounts with RCS accounts which may require a separate page.
- Closes #274, #548

Account info

---

PollBuddy-Server/backend/routes/users.js
PollBuddy-Server/backend/routes/users.test.js

Our backend is down. (Tests are failing)
Problem was from the update to the middlewares and they where fixed how they used to be called. This fixes the router and the tests to update for the status code changes etc that came with the middleware. 
- Write new tests for successfully getting groups of a user. This will come with issue#591
- Closes #XXXX

Backing Testing Fixes

---

PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/components/GroupEditor/GroupEditor.js
PollBuddy-Server/frontend/src/pages/AccountInfo/AccountInfo.js
PollBuddy-Server/frontend/src/pages/AnswerRecorded/AnswerRecorded.js
PollBuddy-Server/frontend/src/pages/LoginWithPollBuddy/LoginWithPollBuddy.js
PollBuddy-Server/frontend/src/pages/LoginWithSchoolStep2/LoginWithSchoolStep2.js
PollBuddy-Server/frontend/src/pages/RegisterWithPollBuddy/RegisterWithPollBuddy.js
PollBuddy-Server/frontend/src/pages/RegisterWithSchoolStep2/RegisterWithSchoolStep2.js

Added push={true} to all redirects as per issue
- (none)
- Closes #465

Fixed redirect tos

---

PollBuddy-Server/frontend/src/pages/AccountInfo/AccountInfo.js
PollBuddy-Server/frontend/src/pages/AccountInfo/AccountInfo.scss

Adds a checkbox in the "Account Info" page which allows the user to select if they would like to log out everywhere after changing their password. Checkbox only displays after the user selects to change their password (as seen in images below).
Please be sure to make sure the `fetch` function in the function `handleLogOutEverywhere` (starts at line 194) works properly with the desired functionality since I am unsure exactly what the backend should be doing to handle the log out request.
- Closes #481 
(I would do before, however the current version has the Account page as just a loading wheel)

Creates a log out everywhere checkbox & closes issue 481

---

PollBuddy-Server/frontend/src/Utils/Validator.js
PollBuddy-Server/frontend/src/components/Question/Question.js
PollBuddy-Server/frontend/src/pages/About/About.test.js
PollBuddy-Server/frontend/src/pages/AccountInfo/AccountInfo.js
PollBuddy-Server/frontend/src/pages/Contact/Contact.js
PollBuddy-Server/frontend/src/pages/GroupCreation/GroupCreation.js
PollBuddy-Server/frontend/src/pages/GroupEdit/GroupEdit.js
PollBuddy-Server/frontend/src/pages/GroupPolls/GroupPolls.js
PollBuddy-Server/frontend/src/pages/Groups/Groups.js
PollBuddy-Server/frontend/src/pages/Homepage/Homepage.js
PollBuddy-Server/frontend/src/pages/LoginWithPollBuddy/LoginWithPollBuddy.js
PollBuddy-Server/frontend/src/pages/LoginWithSchool/LoginWithSchool.js
PollBuddy-Server/frontend/src/pages/PollEditor/PollEditor.js
PollBuddy-Server/frontend/src/pages/PollHistory/PollHistory.js
PollBuddy-Server/frontend/src/pages/PollResults/PollResults.js
PollBuddy-Server/frontend/src/pages/RegisterWithPollBuddy/RegisterWithPollBuddy.js
PollBuddy-Server/frontend/src/pages/RegisterWithSchool/RegisterWithSchool.js
PollBuddy-Server/frontend/src/pages/RegisterWithSchoolStep2/RegisterWithSchoolStep2.js
PollBuddy-Server/frontend/src/pages/ResetPassword/ResetPassword.js
PollBuddy-Server/frontend/src/pages/Template/Template.js

Cleaned up frontend lint warnings
There are a few warnings remaining regarding some of the React objects
- Closes #573

Frontend lint cleanup

---

PollBuddy-Server/frontend/src/pages/RegisterWithPollBuddy/RegisterWithPollBuddy.js
PollBuddy-Server/frontend/src/pages/RegisterWithPollBuddy/RegisterWithPollBuddy.scss
PollBuddy-Server/frontend/src/styles/main.scss
package-lock.json

Added button to show password

---

PollBuddy-Server/backend/app.js

Added error json response with 404 status code
Removed CreateError function inside next()
- (none)
- Closes #628

fix(backend): format 404 error as a JSON response.

---

PollBuddy-Server/backend/.eslintrc.json
PollBuddy-Server/backend/routes/polls.js

Turned on switch-case indention checking in the backend eslint config
- (none)
- (none)

Small backend lint change from a long time ago to fix a switch case indention issue

---

PollBuddy-Server/backend/package-lock.json
PollBuddy-Server/backend/package.json
PollBuddy-Server/frontend/Dockerfile.dev
PollBuddy-Server/frontend/hotreload-fix.js
PollBuddy-Server/frontend/package-lock.json
PollBuddy-Server/frontend/package.json

Thanks to a fix found here: https://github.com/facebook/create-react-app/issues/11879#issuecomment-1069553776, hot reloading in the frontend development mode is now fixed :) 
Also, updated packages in both frontend and backend. 
- (none)
- (none)

React hotreload fix and package updates

---

PollBuddy-Server/frontend/src/App.js
PollBuddy-Server/frontend/src/components/Dropdown/Dropdown.js
PollBuddy-Server/frontend/src/components/PrivateComponent/PrivateComponent.js
PollBuddy-Server/frontend/src/components/PropsWrapper/PropsWrapper.js
PollBuddy-Server/frontend/src/pages/AccountInfo/AccountInfo.js
PollBuddy-Server/frontend/src/pages/GroupJoin/GroupJoin.js
PollBuddy-Server/frontend/src/pages/Groups/Groups.js
PollBuddy-Server/frontend/src/pages/LoginDefault/LoginDefault.js
PollBuddy-Server/frontend/src/pages/LoginWithPollBuddy/LoginWithPollBuddy.js
PollBuddy-Server/frontend/src/pages/LoginWithSchoolStep2/LoginWithSchoolStep2.js
PollBuddy-Server/frontend/src/pages/RegisterWithPollBuddy/RegisterWithPollBuddy.js
PollBuddy-Server/frontend/src/pages/RegisterWithSchoolStep2/RegisterWithSchoolStep2.js

Previously, anyone could go to any link without being logged in. I made it so that if you are not logged in, you get redirected to the login page, and then once logged in, it redirects you back to the previous page that you tried to go to prior to logging in.
- (none)
- Closes #632
Using /groups route as an example, this is functionally the same for all other routes that should require login:
When not logged in and going to /groups route before:
When not logged in and going to /groups after(redirects to /login):
Then if logged in successfully, redirects back to /groups:

Redirect to Login and Back

---

PollBuddy-Server/backend/models/Group.js
PollBuddy-Server/backend/models/Poll.js
PollBuddy-Server/backend/modules/modelUtils.js
PollBuddy-Server/backend/modules/testingUtils.js
PollBuddy-Server/backend/routes/groups.js
PollBuddy-Server/backend/routes/groups.test.js
PollBuddy-Server/backend/routes/polls.js
PollBuddy-Server/backend/routes/polls.test.js
PollBuddy-Server/frontend/src/pages/GroupJoin/GroupJoin.js
PollBuddy-Server/frontend/src/pages/PollEditor/PollEditor.js
PollBuddy-Server/frontend/src/pages/PollEditor/PollEditor.scss
docker-compose.dev.yml

Group Code Search Params, Poll Allow Submissions
- (none)
- Closes #XXXX

Poll Allow Submission Fixes

---

PollBuddy-Server/backend/routes/polls.test.js
PollBuddy-Server/backend/routes/users.test.js

Adding tests for the getPollResults function and backend endpoint. Essentially just creates a new poll, adds a question, and then requests the results. This increases the polls.js route to 51.87% coverage, and the Poll.js to 65.21% coverage.
- Nope
- Closes #658

Poll results tests

---

PollBuddy-Server/frontend/src/components/GroupSettings/GroupSettings.js
PollBuddy-Server/frontend/src/pages/Groups/Groups.js

Made some buttons on the groups and group polls page larger so that they were consistent in size to other buttons on those pages.
- (none)
- Closes #662 
Before:
After:

Resized buttons

---

PollBuddy-Server/backend/models/Poll.js
PollBuddy-Server/backend/modules/testingUtils.js
PollBuddy-Server/backend/routes/polls.test.js

Added tests for the editquestions GET and POST routes. Added cases for editing questions as poll creator, admin, and non-admin/poll creator.

Editquestions route tests

---

PollBuddy-Server/frontend/src/pages/PollCreation/PollCreation.js

The error messages when creating a new poll were very general, but now they say either title, description, or both are missing.
- None
- Closes #671

Improved error reporting on new poll creation

---

PollBuddy-Server/backend/app.js
PollBuddy-Server/backend/modules/utils.js
PollBuddy-Server/backend/package-lock.json
PollBuddy-Server/backend/package.json
PollBuddy-Server/backend/routes/groups.js
PollBuddy-Server/backend/routes/polls.js
PollBuddy-Server/backend/routes/users.js

streamlined the and/or system for predicate middleware
removed promote, middleware can now be and/or'ed directly
the meaning of a "predicate" is just a middleware that sends a message on failure and calls next() on success
- (none)
- Closes #681

Predicate rework

---

PollBuddy-Server/backend/models/Poll.js
PollBuddy-Server/frontend/src/components/QuestionResults/QuestionResults.js

Added the number of total responses to the bottom of the results page.
- (none)
- Closes #653
Before:
After:

Total Responses Display

---

PollBuddy-Server/frontend/src/pages/PollResults/PollResults.js

deleted unneeded code
- N/A
- Closes #XXXX

deleted unused code

---

PollBuddy-Server/backend/modules/httpCodes.js

Updated function `sendResponse` to use `res.json()`.
Previously we were using `res. end()` which is not appropriate.
- (none)
- Closes #694

Update sendReponse function to use res.json()

---

PollBuddy-Server/frontend/src/pages/PollViewer/PollViewer.js

- Generate 6 character long Poll ID for ease to use.
- Closes #695

Fix Poll Viewer is empty when no questions

---

PollBuddy-Server/backend/app.js
PollBuddy-Server/backend/models/Group.js
PollBuddy-Server/backend/models/Poll.js
PollBuddy-Server/backend/models/User.js
PollBuddy-Server/backend/modules/modelUtils.js
PollBuddy-Server/backend/modules/testingUtils.js
PollBuddy-Server/backend/modules/utils.js
PollBuddy-Server/backend/package-lock.json
PollBuddy-Server/backend/package.json
PollBuddy-Server/backend/routes/groups.js
PollBuddy-Server/backend/routes/groups.test.js
PollBuddy-Server/backend/routes/polls.js
PollBuddy-Server/backend/routes/polls.test.js
PollBuddy-Server/backend/routes/users.js
PollBuddy-Server/backend/routes/users.test.js
PollBuddy-Server/frontend/src/pages/PollEditor/PollEditor.js
PollBuddy-Server/frontend/src/pages/PollResults/PollResults.js
PollBuddy-Server/frontend/src/styles/main.scss

We needed a good way to get data out of Poll Buddy for external review, such as during Submitty grading. This PR adds that functionality in both the frontend and backend. Buttons were added to the poll editor and results page to download the CSV. Additionally, buttons to open the viewer and results pages were added to the editor. 
- (none)
- Closes #646
- Closes #647
- Closes #701

CSV export backend/frontend functionality

---

.vscode/launch.json
PollBuddy-Server/frontend/src/components/QuestionResults/QuestionResults.js

I added a line in the QuestionResults.js file to change the scaling to 1, so that when there are no poll results, the y-axis doesn't go up by fractional increments. (Ignore the second commit, named "test". It is not part of the issue)
- The .vscode/launch.json file isn't relevant and can be ignored.
- Closes #686

fixed Issue 686

---

.github/workflows/CodeQL.yml
.github/workflows/codeql.yml

The addition of this workflow creates an automated code scanning which will make it easier to check for issues in our code. 
- (none)
- Closes #697

Automated Code Scanning

---

kubernetes/backend.yml
kubernetes/frontend.yml
kubernetes/reporting-frontend.yml

- Renovations to the Kubernetes CICD setup
- Fixed the DNS issue causing containers to restart a lot
- 
- (none)
- Closes #XXXX

Kubernetes fixes

---

PollBuddy-Server/backend/app.js

- Fixed the backend logging to include the proper path, not just the route-specific path. 
- Added HTTP status to logged items
- More to come, WIP
- (none)
- Closes #XXXX

Tweaks to the reporting system

---

PollBuddy-Server/backend/Dockerfile
PollBuddy-Server/backend/Dockerfile.dev
PollBuddy-Server/backend/Dockerfile.lint
PollBuddy-Server/backend/Dockerfile.test
PollBuddy-Server/backend/package-lock.json
PollBuddy-Server/backend/package.json

Updated packages and Node version (to 18). 
- (none)
- (none)
(none)

Updated Node version and packages

---

kubernetes/backend-config.yml
kubernetes/backend-secrets.yml
kubernetes/backend.yml
kubernetes/db-config.yml
kubernetes/db-secrets.yml
kubernetes/db.yml
kubernetes/frontend.yml
kubernetes/reporting-db-config.yml
kubernetes/reporting-db-secrets.yml
kubernetes/reporting-db.yml
kubernetes/reporting-frontend.yml

Fixed an issue in the CICD pipeline where Kubernetes gets really upset if it sees a number instead of a string. Quoting the text that gets replaced should force it to be a string and solve the issue. 
- (none)
- (none)
(none)

Quoted all text that might get replaced to only numbers during CICD
